services:
  - type: web
    name: trao-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py "exchange_items:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_APP
        value: exchange_items
      - key: FLASK_ENV
        value: production
      - key: DB_USERNAME
        sync: postgres
      - key: DB_PASSWORD
        sync: postgres
      - key: DB_HOST
        sync: localhost
      - key: DB_NAME
        sync: trao